apiVersion: v1
kind: Pod
metadata:
  labels:
    run: super-pod
  name: super-pod
spec:
  containers:
  - image: nginx
    name: super-pod
    volumeMounts:
    - name: my-secret-volume
      mountPath: "/etc/mysecret"
      readOnly: true
    envFrom:
    - configMapRef:
        name: my-config
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-secret
  restartPolicy: Never
status: {}
