apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: my-pod-config
  restartPolicy: Never
