apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: my-secret-container
    image: nginx
    volumeMounts:
    - name: my-secret-volume
      mountPath: "/etc/secretvolume"
      readOnly: true
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-pod-secret
